### ISSUE TITLE
Logo not rendering in some pages (Github Hosting) 

### ISSUE THREAD

**Issue by M-Ali-SQU** [M-Ali-SQU/4wheelsauction.github.io#13]
Logo not rendering properly in other pages when hosting using Github page 

![image](https://github.com/user-attachments/assets/b2dc555d-8c36-4395-b13a-9bc98e7f319f)
Figure 1: image of logo that is not rendering

![image](https://github.com/user-attachments/assets/801532aa-d0a3-494b-a4ba-b6361486213f)
Figure 2: Supposed logo

**Comment by Saad-Alismaili** [comment]
You need to add the full path or copy the logo image file for other pages and use it
